const fs = require('fs');

const code = [
"const fs=require('fs');",
"",
"const STATE_PATH='./runtime/kernel_state.json';",
"",
"const queue=[];",
"let running=false;",
"",
"function load(){",
"  try{return JSON.parse(fs.readFileSync(STATE_PATH,'utf8'));}",
"  catch{return {version:'0.0.0',sourceOfTruth:'PIPELINE'};}",
"}",
"",
"function commit(s){",
"  fs.writeFileSync(STATE_PATH,JSON.stringify(s,null,2));",
"}",
"",
"function apply(e,s){",
"  if(e.type==='SET_VERSION'){",
"    s.version=e.version;",
"    s.activeVersion=e.version;",
"  }",
"  return s;",
"}",
"",
"function validate(e,s){",
"  if(!e||!e.type) return {ok:false};",
"  if(s.sourceOfTruth!=='PIPELINE') return {ok:false};",
"  return {ok:true};",
"}",
"",
"async function run(){",
"  if(running) return;",
"  running=true;",
"",
"  while(queue.length){",
"    const e=queue.shift();",
"    let s=load();",
"",
"    const v=validate(e,s);",
"    if(!v.ok) continue;",
"",
"    s=apply(e,s);",
"    commit(s);",
"  }",
"",
"  running=false;",
"}",
"",
"function dispatch(e){",
"  queue.push(e);",
"  run();",
"}",
"",
"module.exports={dispatch};"
].join("\\n");

fs.writeFileSync('./runtime/KERNEL_PIPELINE.js', code);

console.log('PIPELINE INSTALLED OK');
