services:
  - type: web
    name: ima-915m
    runtime: docker
    repo: https://github.com/imaosglobal/Ima-kernel
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
