plugins {
    id 'com.android.application'
}

android {
    namespace "com.ima.core"
    compileSdk 34

    defaultConfig {
        applicationId "com.ima.core"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {}
