from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from .receiver import learn_from_result


def _now() -> str:
    return datetime.now().isoformat()


def evaluate(result: dict) -> dict:
    """
    Decide whether a MEDA result is strong enough to stop
    or whether another research iteration is justified.

    This is deliberately conservative.
    """
    hard_pass = bool(result.get("hard_pass", False))

    constraint = result.get("constraint_score")
    data_score = result.get("data_score")
    fitness = result.get("best_fitness")

    def num(x):
        try:
            return float(x)
        except (TypeError, ValueError):
            return None

    constraint = num(constraint)
    data_score = num(data_score)
    fitness = num(fitness)

    reasons = []

    if not hard_pass:
        reasons.append("hard_constraints_not_passed")

    if constraint is not None and constraint < 0.95:
        reasons.append("constraint_score_below_target")

    if result.get("mode") == "data_anchored":
        if data_score is None:
            reasons.append("missing_data_score")
        elif data_score < 0.80:
            reasons.append("data_score_below_target")

    if not reasons:
        decision = "accept"
    else:
        decision = "continue"

    return {
        "decision": decision,
        "reasons": reasons,
        "hard_pass": hard_pass,
        "constraint_score": constraint,
        "data_score": data_score,
        "fitness": fitness,
        "evaluated_at": _now(),
    }


def ingest_and_evaluate(result: dict) -> dict:
    """
    Complete MEDA -> IMA boundary for one discovery.
    """
    learning = learn_from_result(result)
    evaluation = evaluate(result)

    return {
        "ok": True,
        "learning": learning,
        "evaluation": evaluation,
    }


def run_closed_loop(
    initial_result: dict,
    max_iterations: int = 3,
) -> dict:
    """
    Orchestration shell.

    Iteration 1 is always the supplied MEDA result.
    Future iterations will be generated by the hypothesis/experiment
    planner rather than blindly rerunning the same experiment.
    """
    max_iterations = max(1, int(max_iterations))

    history = []
    current = initial_result

    for iteration in range(1, max_iterations + 1):
        step = ingest_and_evaluate(current)

        history.append(
            {
                "iteration": iteration,
                "evaluation": step["evaluation"],
                "learning": {
                    "ok": step["learning"].get("ok"),
                    "concepts": step["learning"].get(
                        "concepts", []
                    ),
                },
            }
        )

        if step["evaluation"]["decision"] == "accept":
            break

        # Do NOT automatically rerun MEDA yet.
        # A future hypothesis planner must create a genuinely new
        # experiment/model before another MEDA invocation.
        break

    return {
        "ok": True,
        "iterations": len(history),
        "history": history,
        "next_action": (
            "accept"
            if history[-1]["evaluation"]["decision"] == "accept"
            else "generate_new_hypothesis"
        ),
    }
