import os, subprocess, json, random
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(__file__))
EXAMPLES_DIR = os.path.join(ROOT, "examples")
LOG_FILE = os.path.join(ROOT, "ima-agent", "log.json")

DOMAINS = {
    "biology": ["Lotka-Volterra", "Epidemic SIR", "Cell Growth"],
    "physics": ["Pendulum", "Spring-Mass", "Wave Equation"], 
    "finance": ["Stock Price", "Portfolio", "Compound Interest"],
    "chemistry": ["Reaction Rate", "Diffusion", "pH Curve"],
    "sports": ["Basketball Score", "Running Pace", "Game Stats"]
}

def scan_existing():
    done = [d for d in os.listdir(EXAMPLES_DIR) if os.path.isdir(os.path.join(EXAMPLES_DIR,d))]
    print(f"[IMA] Found {len(done)} existing examples: {done}")
    return done

def find_run_file(path):
    for f in os.listdir(path):
        if f.startswith("run") and f.endswith(".py"):
            return os.path.join(path, f)
    return None

def test_example(path):
    run_file = find_run_file(path)
    if not run_file: return False, "no run.py"
    result = subprocess.run(["python", run_file], capture_output=True, text=True, timeout=30)
    return result.returncode == 0, result.stderr

def auto_fix(path, error):
    print(f"[IMA] Attempting auto-fix for {os.path.basename(path)}")
    run_file = find_run_file(path)
    if not run_file: 
        # אם אין run בכלל ניצור אחד
        run_file = os.path.join(path, "run.py")
        with open(run_file, "w") as f: f.write("print('IMA: placeholder run')")
        return True

    with open(run_file, "r") as f: code = f.read()
    fixed = False
    
    if "ModuleNotFoundError" in error and "pandas" in error:
        code = code.replace("import pandas as pd", "")
        fixed = True
    if "FileNotFoundError" in error:
        code = code.replace("pd.read_csv", "# pd.read_csv")
        fixed = True
    if "NameError" in error:
        code = code.replace("{len(x)}", "{{len(x)}}").replace("{y.mean()", "{{y.mean()")
        fixed = True
    
    if fixed:
        with open(run_file, "w") as f: f.write(code)
    return fixed

def self_heal():
    print("[IMA] Starting self-heal scan...")
    examples = scan_existing()
    fixed = []
    for ex in examples:
        path = os.path.join(EXAMPLES_DIR, ex)
        ok, err = test_example(path)
        if not ok:
            print(f"[IMA] {ex} FAILED: {err[:80]}")
            if auto_fix(path, err):
                ok2, _ = test_example(path)
                if ok2:
                    fixed.append(ex)
                    print(f"[IMA] {ex} FIXED!")
    return fixed

def generate_example(name):
    path = os.path.join(EXAMPLES_DIR, f"auto-{name.lower().replace(' ','-')}")
    os.makedirs(path, exist_ok=True)
    code = f'''import numpy as np
print("=== IMA Auto-Explorer: {name} ===")
x = np.linspace(0, 10, 100)
y = np.sin(x) + 0.1*np.random.randn(100)
print(f"Generated {{len(x)}} points. Mean y: {{y.mean():.3f}}")
'''
    with open(os.path.join(path, "run.py"), "w") as f: f.write(code)
    with open(os.path.join(path, "README.md"), "w") as f: 
        f.write(f"# IMA Auto: {name}\n\nGenerated by ima-agent at {datetime.now()}")
    return path

def log_action(action, details):
    log = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE) as f: log = json.load(f)
    log.append({"time": str(datetime.now()), "action": action, "details": details})
    with open(LOG_FILE, "w") as f: json.dump(log[-50:], f)

def push_changes(msg):
    subprocess.run(["git", "add", "examples/", "ima-agent/"])
    subprocess.run(["git", "commit", "-m", msg])
    subprocess.run(["git", "push", "origin", "main"])

if __name__ == "__main__":
    print("=== IMA AUTO-EXPLORER v3.1 WITH MEMORY ===")

    fixed = self_heal()
    if fixed:
        msg = f"auto-fix: repaired {', '.join(fixed)}"
        push_changes(msg)
        log_action("self-heal", fixed)

    done = scan_existing()
    all_domains = [d for v in DOMAINS.values() for d in v]
    todo = [d for d in all_domains if not any(d.lower() in x.lower() for x in done)]
    new_task = random.choice(todo) if todo else random.choice(all_domains)
    print(f"[IMA] I choose to explore: {new_task}")
    log_action("new-example", new_task)

    path = generate_example(new_task)
    ok, _ = test_example(path)
    if ok: 
        push_changes(f"auto: add {os.path.basename(path)}")
        log_action("push", os.path.basename(path))

    log_len = len(json.load(open(LOG_FILE))) if os.path.exists(LOG_FILE) else 0
    print(f"[IMA] Cycle complete. Total actions in memory: {log_len}")
