import numpy as np
import pandas as pd

# Auto-generated by IMA Agent
print("=== IMA Auto-Explorer: Reaction Rate ===")
print("Running pure numpy example...")
x = np.linspace(0, 10, 100)
y = np.sin(x) + 0.1*np.random.randn(100)
print(f"Generated {len(x)} points. Mean y: {y.mean():.3f}")
