plugins {
    id 'com.android.application'
}

android {
    namespace "com.ima.core"
    compileSdk 34

    defaultConfig {
        applicationId "com.ima.core"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.android.billingclient:billing:9.1.0'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
